'use client';
import {
  Home,
  ListTodo,
  GraduationCap,
  Gift,
  FileText,
  User,
  ChevronLeft,
  Award,
  ChevronRight,
  TrendingUp,
  School,
  Bell,
  ShieldCheck,
  Zap,
  Globe,
  Wallet,
  CreditCard,
  ArrowRight,
  Sparkles,
  Search,
  Heart,
  BookOpen,
  MapPin,
  Users,
  X,
  Facebook,
  Instagram,
  Linkedin,
  Youtube,
  Mail,
  Phone,
  Calendar,
} from 'lucide-react';

export {
  Home, ListTodo, GraduationCap, Gift, FileText, User, ChevronLeft, Award, ChevronRight,
  TrendingUp, School, Bell, ShieldCheck, Zap, Globe, Wallet, CreditCard, ArrowRight, Sparkles,
  Search, Heart, BookOpen, MapPin, Users, X, Facebook, Instagram, Linkedin, Youtube, Mail, Phone, Calendar
};
